dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
addons:
  apt:
    packages:
      - libboost-python-dev
      - libgraphicsmagick++1-dev
      - python3-setuptools
      - gsfonts
install: pip install tox-travis
script: tox
